choose-file = 选择文件
zh-CN = 简体中文
en-US = English
supported-files = 支持的文件
drag-and-drop-file-here = 拖拽文件到此处
file = 文件
extension = 扩展名
pdf-file = PDF文件
epub-file = EPub文件
mobi-file = Mobi文件
azw3-file = Azw3文件
archive-file = 压缩文件
guitar-tab-file = Guitar Tab文件
threed-model-file = 3D模型文件
loading-failure = 加载失败